### ISSUE TITLE
Broken After Firefox 53

### ISSUE THREAD

**Issue by tunneln** [JasonAnx/Mozarch#1]
After updating to Firefox 53 it seems that the CSS breaks and simply becomes a dark theme with black fields that won't show text

**Comment by JasonAnx** [comment]
Linux or Windows?

**Comment by tunneln** [comment]
On Linux, more specifically Arch Linux

**Comment by JasonAnx** [comment]
Thanks for letting me know. Unfortunately I can't fix it right now (University and Guitar Orchestra rn :/ ). We'll have to wait until the end of the current semester (~July).
